### ISSUE TITLE
Demo is locked to Google employees?

### ISSUE THREAD

**Issue by nolanlawson** [WICG/longtasks#3]
Unless this page is supposed to be the demo itself, I believe it's locked to non-Googlers: https://x20web.corp.google.com/~panicker/longtask/demo/demo.html

![2016-09-22 04_01_49-up corp google com - moma single sign on](https://cloud.githubusercontent.com/assets/283842/18740733/3d7b05ae-80a3-11e6-9c84-681cd2de8dd8.png)

**Comment by spanicker** [comment]
Long resolved
